version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.3.2
    container_name: mealie
    ports:
        - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M 
    volumes:
      - mealie-data:/app/data/
    environment:
      - ALLOW_SIGNUP={ALLOW_SIGNUP}
      - PUID={PUID}
      - PGID={PGID}
      - TZ={TZ}
      - MAX_WORKERS={MAX_WORKERS}
      - WEB_CONCURRENCY={WEB_CONCURRENCY}
      - BASE_URL={BASE_URL}
      - SMTP_HOST={SMTP_HOST}
      - SMTP_PORT={SMTP_PORT}
      - SMTP_FROM_NAME={SMTP_FROM_NAME}
      - SMTP_AUTH_STRATEGY={SMTP_AUTH_STRATEGY}
      - SMTP_FROM_EMAIL={SMTP_FROM_EMAIL}
      - SMTP_USER={SMTP_USER}
      - SMTP_PASSWORD={SMTP_PASSWORD}
    restart: always

volumes:
  mealie-data:
    driver: local