version: '3.3'
    
services:
 authelia:
    env_file: authelia_env.env
    container_name: authelia
    image: authelia/authelia
    restart: unless-stopped
    ports:
      - 9091:9091
    volumes:
      - ${PWD}/data/authelia/config:/config 
    environment:
      - TZ=${TZ}