volumes:
  nextcloud-data:
  nextcloud-db:

networks:
  nextcloud-traefik:
    driver: bridge
    name: nextcloud-traefik
  backend:

services:
  nextcloud-app:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud-data:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
      - OVERWRITEPROTOCOL=${OVERWRITEPROTOCOL}
      - maintenance_window_start=${maintenance_window_start}
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=nextcloud-traefik'
      #middlewares v2
      - "traefik.http.middlewares.nc-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nc-rep.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-header.headers.customFrameOptionsValue=SAMEORIGIN"

      - "traefik.http.middlewares.nc-header.headers.customresponseheaders.Strict-Transport-Security=max-age=15552000; includeSubDomains; preload"
      #http
      - 'traefik.http.routers.nextcloud-http.entrypoints=web'
     # - 'traefik.http.routers.nextcloud-http.middlewares=redirect-to-https'
      - 'traefik.http.routers.nextcloud-http.rule=Host(`${DOMAIN}`)'
      #https
      - 'traefik.http.routers.nextcloud.entrypoints=websecure'
      - 'traefik.http.routers.nextcloud.middlewares=nc-rep,nc-header'      
      - 'traefik.http.routers.nextcloud.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.nextcloud.tls.certresolver=cloudflare'
      - 'traefik.http.routers.nextcloud.tls=true'
      - 'traefik.http.routers.nextcloud.service=nextcloud'
      - 'traefik.http.services.nextcloud.loadbalancer.server.port=80'
      - 'traefik.http.services.nextcloud.loadbalancer.passHostHeader=true'

    networks:
      - nextcloud-traefik
      - backend

  nextcloud-db:
    image: mariadb:11.4
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - backend