version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
     - 9445:80 
    volumes:
     - /home/piotr/bitwarden:/data:rw
    environment:
     - ADMIN_TOKEN=${ADMIN_TOKEN}
     - WEBSOCKET_ENABLED=true
     - SMTP_HOST=${SMTP_HOST}
     - SMTP_FROM=${SMTP_FROM}
     - SMTP_PORT=${SMTP_PORT}
     - SMTP_SSL=${SMTP_SSL}
     - SMTP_USERNAME=${SMTP_USERNAME}
     - SMTP_PASSWORD=${SMTP_PASSWORD}
     - DOMAIN=${DOMAIN}
     - TZ=${TZ}
    networks:
      - front
      
    labels:
      - traefik.enable=true
      - traefik.http.routers.valut-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.valut-http.entrypoints=web
      - 'traefik.http.routers.valut-https.entrypoints=websecure'    
      - 'traefik.http.routers.valut-https.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.valut-https.tls.certresolver=cloudflare'
      - 'traefik.http.routers.valut-https.tls=true'
networks:
  front:
    external: true