networks:
  vikunja-traefik:
    name: vikunja-traefik
    driver: bridge
  vikunja:
    name: vikunja
    driver: bridge
    
services:
  vikunja:
    image: vikunja/vikunja
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://${DOMAIN}
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_DATABASE_PASSWORD}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: ${VIKUNJA_DATABASE_USER}
      VIKUNJA_DATABASE_DATABASE: ${VIKUNJA_DATABASE_DATABASE}
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SERVICE_JWTSECRET}
      VIKUNJA_SERVICE_ENABLEREGISTRATION: false
    volumes: 
      - /home/piotr/vikunja/files:/app/vikunja/files
    networks:
      - vikunja-traefik
      - vikunja
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - 'traefik.docker.network=vikunja-traefik'
      - traefik.http.routers.vikunja-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.vikunja-http.entrypoints=web
      - 'traefik.http.routers.vikunja-https.entrypoints=websecure'    
      - 'traefik.http.routers.vikunja-https.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.vikunja-https.tls.certresolver=cloudflare'
      - 'traefik.http.routers.vikunja-https.tls=true'
  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - /home/piotr/vikunja/db:/var/lib/mysql
    networks:
      - vikunja
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
      interval: 2s
      start_period: 30s