networks:
  linkwarden-traefik:
    name: linkwarden-traefik
    driver: bridge
  linkwarden:
    name: linkwarden
    driver: bridge
    
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    volumes:
      - /home/piotr/linkwarden/pgdata:/var/lib/postgresql/data
    networks:
      - linkwarden
    environment:
      - POSTGRES_PASSWORD=iuerwbfouejra
  linkwarden:
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=https://${DOMAIN}/api/v1/auth
      - NODE_ENV=production
    restart: always
    # build: . # uncomment to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment to build from source
    ports:
      - 3000:3000
    volumes:
      - /home/piotr/linkwarden/data:/data/data
    depends_on:
      - postgres
      - meilisearch
    labels:
      - 'traefik.docker.network=linkwarden-traefik'
      - traefik.enable=true
      - traefik.http.routers.linkwarden-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.linkwarden-http.entrypoints=web
      - 'traefik.http.routers.linkwarden-https.entrypoints=websecure'    
      - 'traefik.http.routers.linkwarden-https.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.linkwarden-https.tls.certresolver=cloudflare'
      - 'traefik.http.routers.linkwarden-https.tls=true'
    networks:
      - linkwarden
      - linkwarden-traefik
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: always
    volumes:
      - /home/piotr/linkwarden/meili_data:/meili_data
    networks:
      - linkwarden